DYNAMIC_MACRO_ENABLE = yes

# TRACKPAD
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
MOUSEKEY_ENABLE = yes


# need the below in your own rules.mk
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
